# Day 1 - Data PreProcessing - 13 Aug 18

In [1]:
# Import libraries
# NumPy - Library that contains Mathematical functions
# Pandas - Library that contains functions to import and manage datasets
import numpy as np
import pandas as pd

In [15]:
# Import dataset
dataset = pd.read_csv(r'D:\100_Days_of_ML_Code\datasets\Data.csv')
# Seperate out independent variables (features/X) and dependent variables (target/Y)
X = dataset.iloc[:, :-1].values # iloc = interger-location [row_slice, column_slice] => [all rows, all cols except the last one]
Y = dataset.iloc[:, 3].values # [all_rows, last col]

In [24]:
# Handle missing data
from sklearn.preprocessing import Imputer
imputer = Imputer() #default alues are enough
imputer = imputer.fit(X[:, 1:3])
print(imputer)
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [28]:
# Encode categorical data - col 3 (Yes/No)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder = LabelEncoder()
X[:, 0] = label_encoder.fit_transform(X[:, 0]) # for first col
onehotencoder = OneHotEncoder(categorical_features = [0]) # encode for first col
X = onehotencoder.fit_transform(X).toarray()

labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(Y)

In [29]:
# Split dataset inot train and test
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, random_state = 0)

In [32]:
# print(X_train, X_test)
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)
print(X_train, X_test)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]] [[ 0.  0.  0. -1. -1.]
 [ 0.  0.  0.  1.  1.]]
